fix compilation error
Fix compilation error due to unbalanced braces in : 

MD_AD9833.cpp: In member function 'boolean MD_AD9833::setFrequency(MD_AD9833::channel_t, float)':
MD_AD9833.cpp:257:77: error: expected ';' before ')' token
spiSend(freq_select | (uint16_t)((uint32_t)_regFreq[chan] >> 14) & 0x3fff));